In [11]:
# 3rd problem
import math
def bidi(n,p,x):
    b=((math.factorial(n))/(math.factorial(x)*math.factorial(n-x)))*(p**x)*((1-p)**(n-x))
    return b
print(bidi(10,0.5,6))
print(bidi(10,2/3,6))
print(bidi(10,1/3,6))

0.205078125
0.2276075801453031
0.05690189503632578


In [28]:
# 2nd problem
import numpy as np
mat1=np.zeros(shape=(9,9))
c1=input().split()
c2=input().split()
l1=[]
l2=[]


for i in range(len(c1)):
    a=list(map(int,c1[i].split(',')))
    l1.append(a)


for i in range(len(c2)):
    b=list(map(int,c2[i].split(',')))
    l2.append(b)

n1=max(l1)
n1=max(n1)

n2=max(l2)
n2=max(n2)

for i in range(1,n1+1):
    for j in range(i+1,n1+1):
        for k in range(len(l1)):
            if i in l1[k]:
                pos=l1[k].index(i)
               
                for m in range(int(pos),len(l1[k])):
                    if(j==l1[k][m]):
                        
                        mat1[i-1][j-1]=1
                    


for i in range(1,n2+1):
    for j in range(1,i):
        for k in range(len(l2)):
            if i in l2[k]:
                #pos=l1[k].index(i)
               
                for m in range(len(l2[k])):
                    if(j==l2[k][m]):
                        
                        mat1[i-1][j-1]=1
print(mat1)        
matlist1=[]
for i in range(n1):
    j=i+1
    if(j<n1):
        t=mat1[i][j]
        matlist1.append(t)
matlist2=[]
for i in range(1,n2):
    j=i-1
    t=mat1[i][j]
    matlist2.append(t)
a11,a00,a01,a10=0,0,0,0
for i in range(len(matlist1)):
    if(matlist1[i]==0 and matlist2[i]==0):
        a00+=1
    if(matlist1[i]==0 and matlist2[i]==1):
        a01+=1
    if(matlist1[i]==1 and matlist2[i]==0):
        a10+=1
    if(matlist1[i]==1 and matlist2[i]==1):
        a11+=1
smc,jc=0.0,0.0
smc=(a11+a00)/(a11+a10+a01+a00)
jc=(a11)/(a11+a10+a01)
print(smc)
print(jc)
        
                                
                


1,3,4,5 2,6 7 8,9
1,2,3,4 5,6 7,8,9
[[ 0.  0.  1.  1.  1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 1.  1.  0.  1.  1.  0.  0.  0.  0.]
 [ 1.  1.  1.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  1.  1.  0.]]
0.375
0.2857142857142857


In [62]:
#6th problem
import pandas as pd
import numpy as np
excel1=pd.read_excel("C:\\Users\\user\\ex6.xlsx")
yage=0
is_yes=excel1['class'].str.contains('yes')
#if excel1['class']=='yes':
 #   if excel1['age']<=30:
  #      yage+=1
yescount=0
nocount=0
yesage=0
noage=0
yesincome=0
noincome=0
yesstudent=0
nostudent=0
yescredit=0
nocredit=0

for i in range(len(is_yes)):
    
    if is_yes[i]==True:
        
        yescount+=1
    else:
        nocount+=1
for i in range(len(is_yes)):
    
    if is_yes[i]==True:
        if excel1['age'][i]=='<=30':
            yesage+=1
    if is_yes[i]==False:
        if excel1['age'][i]=='<=30':
            noage+=1
yes=yescount/(yescount+nocount)
no=nocount/(yescount+nocount)
e1yes=yesage/yescount
e1no=noage/nocount
for i in range(len(is_yes)):
    
    if is_yes[i]==True:
        if excel1['income'][i]=='medium':
            yesincome+=1
    if is_yes[i]==False:
        if excel1['income'][i]=='medium':
            noincome+=1
e2yes=yesincome/yescount
e2no=noincome/nocount
for i in range(len(is_yes)):
    
    if is_yes[i]==True:
        if excel1['student'][i]=='yes':
            yesstudent+=1
    if is_yes[i]==False:
        if excel1['student'][i]=='yes':
            nostudent+=1
e3yes=yesstudent/yescount
e3no=nostudent/nocount
for i in range(len(is_yes)):
    
    if is_yes[i]==True:
        if excel1['age'][i]=='<=30':
            yesage+=1
    if is_yes[i]==False:
        if excel1['age'][i]=='<=30':
            noage+=1
for i in range(len(is_yes)):
    
    if is_yes[i]==True:
        if excel1['credit'][i]=='fair':
            yescredit+=1
    if is_yes[i]==False:
        if excel1['credit'][i]=='fair':
            nocredit+=1
e4yes=yescredit/yescount
e4no=nocredit/nocount
yese=yes*e1yes*e2yes*e3yes*e4yes
print(yese)
noe=no*e1no*e2no*e3no*e4no
print(noe)
if(yese>noe):
    print('yes')
else:
    print('no')

0.02821869488536155
0.006857142857142858
yes


In [35]:
#7th problem
import pandas as pd
import numpy as np
import math
excel1=pd.read_excel("C:\\Users\\user\\ex7.xlsx")
is_yes=excel1['play'].str.contains('yes')
yescount=0
nocount=0
yesoutlook=0
nooutlook=0
yeswindy=0
nowindy=0
yesmean,yesmeanhum=0,0
nomean,nomeanhum=0,0
yeslist=[]
nolist=[]
yeslisthum=[]
nolisthum=[]
for i in range(len(is_yes)):
    
    if is_yes[i]==True:
        
        yescount+=1
    else:
        nocount+=1
for i in range(len(is_yes)):
    
    if is_yes[i]==True:
        if excel1['outlook'][i]=='overcast':
            yesoutlook+=1
    if is_yes[i]==False:
        
        if excel1['outlook'][i]=='overcast':
            
            nooutlook+=1
yes=yescount/(yescount+nocount)
no=nocount/(yescount+nocount)
e1yes=yesoutlook/yescount
e1no=nooutlook/nocount

       
for i in range(len(is_yes)):
    
    if is_yes[i]==True:
       
        if(excel1['windy'][i]=='no'):
            
            yeswindy+=1
    if is_yes[i]==False:
        if excel1['windy'][i]=='no':
            nowindy+=1

e4yes=yeswindy/yescount
e4no=nowindy/nocount

for i in range(len(is_yes)):
    
    if is_yes[i]==True:
        yesmean+=excel1['temp'][i]
        yeslist.append(excel1['temp'][i])
    else:
        nomean+=excel1['temp'][i]
        nolist.append(excel1['temp'][i])
yesmean=yesmean/yescount
nomean=nomean/nocount
yesnumpy=np.array(yeslist)
nonumpy=np.array(nolist)
yesstd=yesnumpy.std()
nostd=nonumpy.std()
mean, std = yesmean, yesstd
cdfyes = lambda x: 0.5 * (1 + math.erf((x - mean) / (std * (2 ** 0.5))))
e2yes=cdfyes(60)
mean, std = nomean, nostd
cdfno = lambda x: 0.5 * (1 + math.erf((x - mean) / (std * (2 ** 0.5))))
e2no=cdfno(60)

for i in range(len(is_yes)):
    
    if is_yes[i]==True:
        yesmeanhum+=excel1['humidity'][i]
        yeslisthum.append(excel1['humidity'][i])
    else:
        nomeanhum+=excel1['humidity'][i]
        nolisthum.append(excel1['humidity'][i])
yesmeanhum=yesmeanhum/yescount
nomeanhum=nomeanhum/nocount
yesnumpyhum=np.array(yeslisthum)
nonumpyhum=np.array(nolisthum)
yesstdhum=yesnumpyhum.std()
nostdhum=nonumpyhum.std()
mean, std = yesmeanhum, yesstdhum
cdfyeshum = lambda x: 0.5 * (1 + math.erf((x - mean) / (std * (2 ** 0.5))))
e3yes=cdfyeshum(60)
mean, std = nomeanhum, nostdhum
cdfnohum = lambda x: 0.5 * (1 + math.erf((x - mean) / (std * (2 ** 0.5))))
e3no=cdfnohum(60)
yese=yes*e1yes*e2yes*e3yes*e4yes
noe=no*e1no*e2no*e3no*e4no

if(yese>noe):
    print('yes')
else:
    print('no')



yes


t**3*x_i**(t - 1)*x_i**(2*t - 2)


In [15]:
#4th problem
from sympy import *
import numpy as np
import math
def ncr(n,x):
    b=((math.factorial(n))/(math.factorial(x)*math.factorial(n-x)))
    return b
n=int(input('enter n value'))
r=int(input('enter r value'))
com=ncr(n,r)
p=Symbol('p')
y=com*(p**r)*((1-p)**(n-r))
dif=y.diff(p)
val=solve(dif,p)
for i in range(len(val)):
    if(val[i]!=0 and val[i]!=1):
        res=val[i]
print(res)


enter n value10
enter r value6
0.600000000000000


In [18]:
#1st problem
l1=[int(x) for x in input().split()]
l2=[int(x) for x in input().split()]
a11,a00,a01,a10=0,0,0,0
for i in range(len(l1)):
    if(l1[i]==0 and l2[i]==0):
        a00+=1
    if(l1[i]==0 and l2[i]==1):
        a01+=1
    if(l1[i]==1 and l2[i]==0):
        a10+=1
    if(l1[i]==1 and l2[i]==1):
        a11+=1
smc,jc=0.0,0.0
smc=(a11+a00)/(a11+a10+a01+a00)
jc=(a11)/(a11+a10+a01)
print(smc)
print(jc)
        
          

1 1 0 1
1 0 0 1
0.75
0.6666666666666666


In [ ]:
#5th problem
from sympy import *
import numpy as np
x=float(input('enter value for x'))
y=float(input('enter value for y'))
z=float(input('enter value for z'))
t=Symbol('t')
l=[]
l.append(x)
l.append(y)
l.append(z)
y=1
for i in range(len(l)):
    
    y=y*t*(l[i]**(t-1))
m=log(y)

val=m.diff(t)

res=solve(val,t)
print(res[0])


In [ ]:
9999